nametag:
  build: .
  dockerfile: nametagDockerfile
  volumes:
    - ./dist:/usr/app/
    - ./.keys:/usr/.keys
    - ./.hz:/usr/app/.hz
    - ./server/src:/usr/server/src
    - ./server/starthz.sh:/usr/server/starthz.sh
    - ./server/backup.sh:/usr/server/backup.sh
    - ./server/backup:/usr/server/backup
  links:
    - rethinkdb
    - redis
  ports:
    - "8181:8181"
    - "8185:8185"
rethinkdb:
  image: rethinkdb
  command: rethinkdb --bind "all"
  volumes:
    - ./rethinkdb_data/:/var/lib/rethinkdb/instances.d
  ports:
    - "28015:28015"
    - "8080:8080"
redis:
  image: redis
  ports:
    - "6379:6379"
