horizon:
  build: .
  dockerfile: devDockerfile
  volumes:
    - ./dist:/usr/app/dist
    - ./.keys:/usr/.keys
    - ./.hz:/usr/app/.hz
    - ./server/app.js:/usr/server/app.js
    - ./server/secrets.json:/usr/server/secrets.json
  links:
    - rethinkdb
  ports:
    - "8181:8181"
rethinkdb:
  image: rethinkdb
  command: rethinkdb --bind "all" #--no-update-check
  ports:
    - "28015:28015"
    - "8080:8080"
# horizon:
#   image: rethinkdb/horizon
#   command: su -s /bin/sh horizon -c "/usr/app/.hz/starthz.sh"
