nametag:
  build: .
  dockerfile: nametagDockerfile
  environment:
    - NODE_ENV=${NODE_ENV}
  volumes:
    - ./dist:/usr/client/
    - ./.keys:/usr/.keys
    - ./.hz:/usr/client/.hz
    - ./server/src:/usr/server/src
    - ./server/starthz.sh:/usr/server/starthz.sh
    - ./server/backup.sh:/usr/server/backup.sh
    - ./server/backup:/usr/server/backup
  links:
    - rethinkdb
    - redis
    - elasticsearch
  ports:
    - "8181:8181"
    - "8185:8185"
rethinkdb:
  image: rethinkdb
  command: rethinkdb --bind "all" #--http-tls-key /usr/.keys/privkey.pem --http-tls-cert /usr/.keys/cert.pem
  volumes:
    - ./rethinkdb_data/:/var/lib/rethinkdb/instances.d
    - ./.keys:/usr/.keys
  expose:
    - "28015"
  ports:
    - "8080:8080"
redis:
  image: redis
  ports:
    - "6379:6379"
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
      - cluster.name=nametag-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
