horizon:
  build: .
  dockerfile: devDockerfile
  volumes:
    - ./dist:/usr/app/
    - ./.keys:/usr/.keys
    - ./.hz:/usr/app/.hz
    - ./server/src:/usr/server/src
    - ./server/schema.toml:/usr/server/schema.toml
    - ./server/starthz.sh:/usr/server/starthz.sh
    - ./horizon:/usr/server/horizon
  links:
    - rethinkdb
  ports:
    - "8181:8181"
  restart_policy:
    condition: "any"
rethinkdb:
  image: rethinkdb
  command: rethinkdb --bind "all" --no-update-check
  volumes:
    - ./rethinkdb_data/:/var/lib/rethinkdb/instances.d
  ports:
    - "28015:28015"
    - "8080:8080"
# horizon:
#   image: rethinkdb/horizon
#   command: su -s /bin/sh horizon -c "/usr/app/.hz/starthz.sh"
