nametag:
  build: .
  dockerfile: nametagDockerfile
  env_file:
    - .env
  volumes:
    - ./dist:/usr/client/
    - ./.keys:/usr/.keys
    - ./.hz:/usr/client/.hz
    - .:/usr/nametag/
    - ./server/backup:/usr/nametag/server/backup
  links:
    - rethinkdb
    - redis
    # - elasticsearch
  ports:
    - "8181:8181"
    - "8185:8185"
rethinkdb:
  image: rethinkdb
  command: rethinkdb --bind "all" #--http-tls-key /usr/.keys/privkey.pem --http-tls-cert /usr/.keys/cert.pem
  volumes:
    - ./rethinkdb_data/:/var/lib/rethinkdb/instances.d
    - ./.keys:/usr/.keys
  expose:
    - "28015"
  ports:
    - "127.0.0.1:8080:8080"
redis:
  image: redis:alpine
  ports:
    - "6379:6379"
  command: redis-server /usr/local/etc/redis/redis.conf
  volumes:
    - ./redis_data:/data
    - ./redis_conf:/usr/local/etc/redis/
# elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
#     environment:
#       - cluster.name=nametag-cluster
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     mem_limit: 1g
#     volumes:
#       - esdata1:/usr/share/elasticsearch/data
#     ports:
#       - 9200:9200
